*** Starting uWSGI 2.0.17 (64bit) on [Thu Jul 12 21:21:14 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 08 July 2018 09:54:22
os: Linux-3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018
nodename: instance-2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/s0913031/notebook/camelq
writing pidfile to /home/s0913031/notebook/camelq/camelq.pid
detected binary path: /home/s0913031/.pyenv/versions/3.6.4rc1/bin/uwsgi
chdir() to /home/s0913031/notebook/camelq
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:9001 fd 3
uwsgi socket 0 bound to TCP address 127.0.0.1:9000 fd 6
Python version: 3.6.4rc1 (default, Jul  8 2018, 18:35:33)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Python main interpreter initialized at 0x183e250
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 486672 bytes (475 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x183e250 pid: 1844 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1844)
spawned uWSGI worker 1 (pid: 1846, cores: 1)
spawned uWSGI worker 2 (pid: 1847, cores: 1)
spawned uWSGI worker 3 (pid: 1848, cores: 1)
spawned uWSGI worker 4 (pid: 1849, cores: 1)
spawned uWSGI worker 5 (pid: 1850, cores: 1)
spawned uWSGI http 1 (pid: 1851)
*** Starting uWSGI 2.0.17 (64bit) on [Thu Jul 12 21:24:51 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 08 July 2018 09:54:22
os: Linux-3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018
nodename: instance-2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/s0913031/notebook/camelq
writing pidfile to /home/s0913031/notebook/camelq/camelq.pid
detected binary path: /home/s0913031/.pyenv/versions/3.6.4rc1/bin/uwsgi
chdir() to /home/s0913031/notebook/camelq
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:9001).
bind(): Address already in use [core/socket.c line 769]
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1847|app: 0|req: 1/1] 126.116.170.149 () {44 vars in 783 bytes} [Thu Jul 12 12:26:55 2018] GET / => generated 55777 bytes in 178 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1848|app: 0|req: 1/2] 126.116.170.149 () {44 vars in 760 bytes} [Thu Jul 12 12:26:56 2018] GET /favicon.ico => generated 55864 bytes in 37 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1849|app: 0|req: 1/3] 89.178.17.0 () {46 vars in 1503 bytes} [Thu Jul 12 12:27:06 2018] GET / => generated 56665 bytes in 37 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1850|app: 0|req: 1/4] 126.116.170.149 () {46 vars in 814 bytes} [Thu Jul 12 12:31:21 2018] GET / => generated 55912 bytes in 36 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1846|app: 0|req: 1/5] 126.116.170.149 () {44 vars in 760 bytes} [Thu Jul 12 12:31:21 2018] GET /favicon.ico => generated 55864 bytes in 36 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1847|app: 0|req: 2/6] 126.116.170.149 () {46 vars in 814 bytes} [Thu Jul 12 12:31:25 2018] GET / => generated 55912 bytes in 28 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '35.200.55.35'. You may need to add '35.200.55.35' to ALLOWED_HOSTS.
[pid: 1848|app: 0|req: 2/7] 126.116.170.149 () {44 vars in 760 bytes} [Thu Jul 12 12:31:25 2018] GET /favicon.ico => generated 55864 bytes in 27 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17 (64bit) on [Thu Jul 12 21:37:24 2018] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 08 July 2018 09:54:22
os: Linux-3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018
nodename: instance-2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/s0913031/notebook/camelq
writing pidfile to /home/s0913031/notebook/camelq/camelq.pid
detected binary path: /home/s0913031/.pyenv/versions/3.6.4rc1/bin/uwsgi
chdir() to /home/s0913031/notebook/camelq
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:9001 fd 3
uwsgi socket 0 bound to TCP address 127.0.0.1:9000 fd 6
Python version: 3.6.4rc1 (default, Jul  8 2018, 18:35:33)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Python main interpreter initialized at 0x1355250
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 486672 bytes (475 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1355250 pid: 1336 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1336)
spawned uWSGI worker 1 (pid: 1338, cores: 1)
spawned uWSGI worker 2 (pid: 1339, cores: 1)
spawned uWSGI worker 3 (pid: 1340, cores: 1)
spawned uWSGI worker 4 (pid: 1341, cores: 1)
spawned uWSGI worker 5 (pid: 1342, cores: 1)
spawned uWSGI http 1 (pid: 1343)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/s0913031/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/s0913031/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/s0913031/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./sites/modules/market.py", line 15, in main
    l = cyptowat.ohlc('bitfinex', 'btcusd', '900')
  File "./model/market/cyptowat.py", line 20, in ohlc
    return res['result_info']['result'][str(periods)]
TypeError: list indices must be integers or slices, not str
[pid: 1339|app: 0|req: 1/1] 126.116.170.149 () {46 vars in 814 bytes} [Thu Jul 12 12:38:02 2018] GET / => generated 83961 bytes in 2680 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 1340|app: 0|req: 1/2] 126.116.170.149 () {48 vars in 813 bytes} [Thu Jul 12 12:38:06 2018] GET /favicon.ico => generated 2602 bytes in 73 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
